@startuml

[Client] as client
[Job Server A] as serverA
[Job Server B] as serverB
[Job Server C] as serverC
'[Database] as db

client <..> serverA
client <..> serverB
client <..> serverC

'server <..> db

@enduml
